# Generated by Django 5.2.6 on 2025-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_customuser_name_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
