# Generated by Django 5.2.6 on 2025-12-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_user_branch_user_college_id_user_hostel_block_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
